apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-prod

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: flask-replicas-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: mysql-secret
    literals:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
