apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-mysql-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
